language: php

php:
  - '7.1'

install:
  - composer self-update 1.10.16
  - composer --version
  - composer install --no-interaction --prefer-source --no-dev

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs src --standard=psr2
